<br><br>
<b><font size=100>NUMPY</font></b>
<br>
<br>
By अंkur गोswami
____

In [1]:
import numpy as np

____
# Creating NumPy Arrays:

## numpy.array()

It takes list/tuple as an argument and returns a NumPy array.

In [4]:
np.array([10,20,30])

array([10, 20, 30])

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## numpy.arange()

It takes start,stop,step as its arguments and returns a NumPy array starting from 'start' to 'stop' with step-size of 'step'.

In [6]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

## numpy.zeros()

It takes integer/tuple as an argument and returns a matrix of given order having value of each element 0.

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## numpy.ones()

It takes integer/tuple as an argument and returns a matrix of given order having value of each element 1.

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## numpy.linspace()

It takes first,second,n as its argument and returns a NumPy array with linearly spaced numbers 'n' numbers between 'first' & 'second'.

In [11]:
np.linspace(10,100,20)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

## numpy.eye()

It takes an argument n and returns a NumPy identity matrix of order n.

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## numpy.random.randint()

It takes low, high, order(can be a list/tuple/integer) as its arguments and returns a NumPy matrix with random integer values between low(inclusive) and high(exclusive) of order provided.

In [13]:
np.random.randint(0,100,(5,5))

array([[62, 87, 81, 95, 38],
       [58, 17, 36, 10, 71],
       [40, 36, 59, 13, 74],
       [65, 90, 57, 25, 50],
       [65, 73, 46, 46, 40]])

## numpy.random.random()

It takes order(can be a list/tuple/integer) as its argument and returns a NumPy matrix with random values between 0(inclusive) and 1(exclusive) of order provided.

In [14]:
np.random.random((5,5))

array([[0.65425825, 0.29352074, 0.31063509, 0.76019599, 0.68046769],
       [0.4363963 , 0.82739079, 0.60465417, 0.19407933, 0.9277395 ],
       [0.71837147, 0.80972326, 0.84017033, 0.21691793, 0.99805139],
       [0.40940252, 0.2904984 , 0.83240094, 0.50643752, 0.75480287],
       [0.38884072, 0.38898771, 0.01222365, 0.35478348, 0.97923728]])

____
# NumPy Array Operations/Methods:

In [15]:
a=np.array([99, 83, 78, 25,  8, 11, 18, 10, 81,  9, 54, 27, 70, 55, 54,  0, 44,26, 57, 38, 33, 92, 68, 44,  6])
a

array([99, 83, 78, 25,  8, 11, 18, 10, 81,  9, 54, 27, 70, 55, 54,  0, 44,
       26, 57, 38, 33, 92, 68, 44,  6])

## numpy.reshape() or array.reshape()

``np.reshape()`` takes an array and order(can be a list/tuple/integer) as its arguments and returns a NumPy matrix having values as same of given array of order provided.

``array.reshape()`` is a method of numpy arrays with only takes order(can be a list/tuple/integer) and converts it into matrix of order provided.

In [16]:
np.reshape(a,(5,5))

array([[99, 83, 78, 25,  8],
       [11, 18, 10, 81,  9],
       [54, 27, 70, 55, 54],
       [ 0, 44, 26, 57, 38],
       [33, 92, 68, 44,  6]])

In [17]:
a.reshape((5,5))

array([[99, 83, 78, 25,  8],
       [11, 18, 10, 81,  9],
       [54, 27, 70, 55, 54],
       [ 0, 44, 26, 57, 38],
       [33, 92, 68, 44,  6]])

## numpy.shape() or array.shape

``np.shape()`` takes an array as its argument and returns order of array.

``array.shape`` is an attribute of numpy arrays which returns order of array.

In [18]:
np.shape(a)

(25,)

In [19]:
a.shape

(25,)

## numpy.dtype() or array.dtype

``np.dtype()`` takes an array as its argument and returns type of array.

``array.dtype`` is a method of numpy arrays which returns type of array.

In [20]:
np.dtype(a)

TypeError: data type not understood

In [21]:
a.dtype

dtype('int32')

## Shallow Copy:

In [22]:
a_shallow=a[:]     #Unlike Lists, it shallow copies the array. Conserves memory.
a_shallow          #It's just a view of original array.

array([99, 83, 78, 25,  8, 11, 18, 10, 81,  9, 54, 27, 70, 55, 54,  0, 44,
       26, 57, 38, 33, 92, 68, 44,  6])

In [23]:
a_shallow[20:]=100     #Broadcasting
a_shallow

array([ 99,  83,  78,  25,   8,  11,  18,  10,  81,   9,  54,  27,  70,
        55,  54,   0,  44,  26,  57,  38, 100, 100, 100, 100, 100])

In [24]:
a

array([ 99,  83,  78,  25,   8,  11,  18,  10,  81,   9,  54,  27,  70,
        55,  54,   0,  44,  26,  57,  38, 100, 100, 100, 100, 100])

Note: array a_shallow is exactly equal to array a.

## Deep Copy using array.copy():

``array.copy()`` is a method of numpy arrays which return a deep copy an array.

In [25]:
a_deep=a.copy()
a_deep

array([ 99,  83,  78,  25,   8,  11,  18,  10,  81,   9,  54,  27,  70,
        55,  54,   0,  44,  26,  57,  38, 100, 100, 100, 100, 100])

In [26]:
a_deep[20:]=200   #Broadcasting

In [27]:
a_deep

array([ 99,  83,  78,  25,   8,  11,  18,  10,  81,   9,  54,  27,  70,
        55,  54,   0,  44,  26,  57,  38, 200, 200, 200, 200, 200])

In [28]:
a

array([ 99,  83,  78,  25,   8,  11,  18,  10,  81,   9,  54,  27,  70,
        55,  54,   0,  44,  26,  57,  38, 100, 100, 100, 100, 100])

Note: array a_deep is not equal to array a.

____
# Accessing NumPy Array Elements:

In [29]:
a=np.arange(0,100)
a=a.reshape((10,10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Double Bracket Notation:

In [30]:
a[1][2]

12

## Single Bracket Notation:

In [31]:
a[1,2]

12

## Fancy Indexing:

In [35]:
a[[2,9,4,7,1,0]]    #Notice there are 2 square brackets. Can be of any order.

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

## Slicing Sub-Matrix:

In [44]:
a[:2,1:]   #Upper right 2X2 matrix

array([[2, 3],
       [5, 6]])

In [54]:
a[[2,0,1]]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

<a id='Mathematical_operations'></a>

____
# Mathematical Operations on NumPy Array:

In [26]:
a=np.arange(0,25)
a=a.reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Addition:

### Scalar Addition:

In [4]:
a+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

### Array Addition:

In [43]:
a*a

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

Same for Subtraction, Multiplication and Modulus.

## Division:

### Scalar Division:

In [6]:
2/a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222],
       [0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714],
       [0.13333333, 0.125     , 0.11764706, 0.11111111, 0.10526316],
       [0.1       , 0.0952381 , 0.09090909, 0.08695652, 0.08333333]])

### Array Division:

In [7]:
a/a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

## Comparing every element:

In [9]:
a%5!=0         #Similar for >,<,==,!=,etc.

array([[False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [10]:
a[a%5!=0]

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19, 21,
       22, 23, 24])

## numpy.min() or array.min()

``np.min()`` takes an array as its argument and returns minimum value of array.

``array.min()`` is a method of numpy arrays with no argument which return minimum value of array.

In [11]:
np.min(a)

0

In [12]:
a.min()

0

## numpy.argmin() or array.argmin()

``np.argmin()`` takes an array as its argument and returns index of mninimum value of array.

``array.argmin()`` is a method of numpy arrays with no argument which returns index of minimum value of array.

In [13]:
np.argmin(a)

0

In [14]:
a.argmin()

0

## numpy.max() or array.max()

``np.max()`` takes an array as its argument and returns maximum value of array.

``array.max()`` is a method of numpy arrays with no argument which returns maximum value of array.

In [15]:
np.max(a)

24

In [16]:
a.max()

24

## numpy.argmax() or array.argmax()

``np.argmax()`` takes an array as its argument and returns index of maximum value of array.

``array.argmax()`` is a method of numpy arrays with no argument which returns index of maximum value of array.

In [17]:
np.argmax(a)

24

In [18]:
a.argmax()

24

## numpy.mean() or array.mean()

``np.mean()`` takes an array as its argument and returns mean of array.

``array.mean()`` is a method of numpy arrays which returns mean of array.

In [19]:
np.mean(a)

12.0

In [20]:
a.mean()

12.0

## numpy.sum() or array.sum()

``np.sum()`` takes an array as its argument and returns sum of array.

``array.sum()`` is a method of numpy arrays which returns sum of array.

In [21]:
np.sum(a)

300

In [24]:
a.sum()

300

On specifying the ``axis`` we can find sum along the given axis. For n dimensional array, we have 0 to n-1 axes.
Example: In a 2-D array, a.sum(axis=0) returns sum  of each column and a.sum(axis=1) returns sum of each row.
<img src=https://i.stack.imgur.com/gj5ue.jpg>
<b>Remember:</b> Axis is 0 for columns and 1 for rows.

## Square root:

In [106]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

## Cube root:

In [107]:
np.cbrt(a)

array([[0.        , 1.        , 1.25992105, 1.44224957, 1.58740105],
       [1.70997595, 1.81712059, 1.91293118, 2.        , 2.08008382],
       [2.15443469, 2.22398009, 2.28942849, 2.35133469, 2.41014226],
       [2.46621207, 2.5198421 , 2.57128159, 2.62074139, 2.66840165],
       [2.71441762, 2.75892418, 2.80203933, 2.84386698, 2.88449914]])

## Raising Power:

In [109]:
np.power(a,2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

We can also use ``**`` operator for raising power.

## Sine:

In [111]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

Same for other trigonometric ratios.

## Exponent:

In [112]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10]])

## Logarithm:

In [131]:
np.log(a)   #Natural Log

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

____
# Linear Operations:

In [21]:
arr=np.random.randint(0,100,(5,5))
arr_1=np.random.randint(0,100,(5,5))
print(arr,arr_1,sep='\n\n')

[[68 41 43 78 95]
 [95 39 50 54  3]
 [21 18 43 51 15]
 [85 68 25 84 56]
 [34 26 13  5 27]]

[[97 23 24 58 51]
 [92 87 27 63 32]
 [77 40 19 48 32]
 [64 59 69 76 60]
 [44 92 68  0  2]]


## Matrix Product:

`numpy.linalg.mutidot()` takes a tuple/list of arrays/matrices and returns their matrix product. The matrix product depends on the order of array/matrices.

In [30]:
np.linalg.multi_dot((arr,arr_1,arr))

array([[5404560, 3275550, 3160670, 4932824, 3573160],
       [4199622, 2676717, 2279504, 3864080, 3184939],
       [2564042, 1603232, 1437451, 2343655, 1787227],
       [5597720, 3452579, 3174422, 5102666, 3848721],
       [1748597, 1055052,  998103, 1587546, 1205580]])

`numpy.matmul()` takes 2 arrays/matrices and returns their matrix product. The matrix product depends on the order of array/matrices.

In [31]:
np.matmul(arr,arr_1)

array([[22851, 20193, 15398, 14519, 11026],
       [20241, 11040,  8213, 14471, 10939],
       [10928,  8158,  6346,  8292,  6113],
       [24266, 18979, 13955, 16798, 12463],
       [ 8199,  6343,  3946,  4614,  3336]])

`numpy.dot()` takes 2 arrays/matrices and returns their matrix product. The matrix product depends on the order of array/matrices.

In [32]:
np.dot(arr,arr_1)

array([[22851, 20193, 15398, 14519, 11026],
       [20241, 11040,  8213, 14471, 10939],
       [10928,  8158,  6346,  8292,  6113],
       [24266, 18979, 13955, 16798, 12463],
       [ 8199,  6343,  3946,  4614,  3336]])

In [33]:
arr@arr_1

array([[22851, 20193, 15398, 14519, 11026],
       [20241, 11040,  8213, 14471, 10939],
       [10928,  8158,  6346,  8292,  6113],
       [24266, 18979, 13955, 16798, 12463],
       [ 8199,  6343,  3946,  4614,  3336]])

<b>Note:</b> Using `@` between two arrays/matrices works same as `numpy.matmul()` & `numpy.dot()`.

In [37]:
np.linalg.eigvals(arr)

array([242.43237321 +0.j        , -15.11953572+31.2040498j ,
       -15.11953572-31.2040498j ,  24.40334912+17.01936763j,
        24.40334912-17.01936763j])

## Determinant:

`numpy.linalg.det()` takes a matrix as its argument and returns the determinant of the matrix.

In [38]:
np.linalg.det(arr)

258008310.00000006

## Inverse:

`numpy.linalg.inv()` takes a matrix as its argument and returns inverse of the matrix.

In [39]:
np.linalg.inv(arr)

array([[ 9.57566832e-03,  1.77633116e-02, -2.36620053e-02,
        -5.25273779e-03, -1.16257418e-02],
       [-2.58888677e-02, -1.82015572e-02,  2.37554984e-02,
         1.88933256e-02,  4.07291998e-02],
       [-2.04995723e-03,  7.53208298e-04,  2.59025843e-02,
        -1.58292576e-02,  2.55698508e-02],
       [ 3.01058133e-03,  5.56183636e-06,  8.03617527e-04,
         1.05811902e-02, -3.29860306e-02],
       [ 1.33012731e-02, -5.20487499e-03, -5.69949859e-03,
        -5.91699934e-03,  6.25326370e-03]])

## Eigen values/vectors:

`numpy.linalg.eig()` takes a matrix as its argument and returns a tuple of eigen values and eigen vectors.

In [45]:
np.linalg.eig(arr)

(array([242.43237321 +0.j        , -15.11953572+31.2040498j ,
        -15.11953572-31.2040498j ,  24.40334912+17.01936763j,
         24.40334912-17.01936763j]),
 array([[-0.54550899+0.j        , -0.32460686+0.3232995j ,
         -0.32460686-0.3232995j , -0.3115552 -0.15006403j,
         -0.3115552 +0.15006403j],
        [-0.48387301+0.j        ,  0.786082  +0.j        ,
          0.786082  -0.j        ,  0.31682908+0.08344963j,
          0.31682908-0.08344963j],
        [-0.26885366+0.j        , -0.03009304+0.12680888j,
         -0.03009304-0.12680888j,  0.69873098+0.j        ,
          0.69873098-0.j        ],
        [-0.60454001+0.j        , -0.18931396-0.21701545j,
         -0.18931396+0.21701545j, -0.20440284+0.35894947j,
         -0.20440284-0.35894947j],
        [-0.17474533+0.j        ,  0.00762153-0.26870663j,
          0.00762153+0.26870663j, -0.11531836-0.3176808j ,
         -0.11531836+0.3176808j ]]))

`numpy.linalg.eigvals()` takes a matrix as its argument and returns eigen values.

In [49]:
np.linalg.eigvals(arr)

array([242.43237321 +0.j        , -15.11953572+31.2040498j ,
       -15.11953572-31.2040498j ,  24.40334912+17.01936763j,
        24.40334912-17.01936763j])

## Matrix Power:

`numpy.linalg.matrix_power()` takes 2 arguments, matrix & power(in integer) and returns matrix raised to power provided.

In [62]:
np.linalg.matrix_power(arr,2)

array([[19282, 12935, 10008, 16738, 14161],
       [15907, 10066,  9574, 16617, 12997],
       [ 8886,  6195,  5122,  9162,  5955],
       [21809, 13755, 10958, 18913, 14870],
       [ 6398,  3684,  3797,  5274,  4512]])

## Matrix Rank:

`numpy.linalg.matrix_rank()` takes matrix as its argument & returns rank of matrix provided.

In [63]:
np.linalg.matrix_rank(arr)

5