<br><br>
<b><font size=100>TENSORFLOW</font></b>
<br>
<br>
By अंkur गोswami
____

In [1]:
import tensorflow as tf

____
# Tensorflow Version:

In [2]:
tf.__version__

'1.13.1'

___
# Constants:

## Creating Constants:

### tf.constant()
`tf.constant()` takes a value and creates a constant of the value given.

In [3]:
name=tf.constant('Ankur Goswami')

`print(name)` doesn't return the value. But it returns type of data the constant holds & it's shape(in case of matrices).<br>
Below is an example.

In [4]:
print(name)

Tensor("Const:0", shape=(), dtype=string)


___
# Sessions:
Sessions are created and executed to do the actual computation. In tensorflow, creating constants/variables and applying operations doesn't actually compute those operations on them. We need to create and run sessions for them.

## Creating Sessions:
Sessions are created just by instantiating `Session` class.

In [5]:
sess=tf.Session()

## Executing Sessions:
Sessions are executed using `.run()` method.

In [6]:
sess.run(name)

b'Ankur Goswami'

## Terminating Sessions:
Sessions can be terminated using `.close()` method.

In [7]:
sess.close()

__Note__: We can also use `with-as` python keyword to execute sessions. This avoids writing a terminating session statement.

___
# Tensors
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

## Creating Tensors:

In [8]:
sess=tf.Session()

### tf.fill()
``tf.fill()`` takes two arguments. One being the shape(tuple) of the tensor and other being the value. This functions creates a tensor of shape given, with all values equal to the value provided.

In [9]:
sess.run(tf.fill((3,5),10))

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

### tf.zeros()
``tf.zeros()`` takes shape(tuple) as its argument. This functions creates a tensor of shape given, with all values equal to the 0.

In [10]:
sess.run(tf.zeros((4,2)))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

### tf.ones()
``tf.ones()`` takes shape(tuple) as its argument. This functions creates a tensor of shape given, with all values equal to the 1.

In [11]:
sess.run(tf.ones((2,2)))

array([[1., 1.],
       [1., 1.]], dtype=float32)

### tf.random_normal()
`tf.random_normal()` takes shape(tuple) as its argument. In addition, it also takes `mean` and `standard deviation`.  This functions creates a tensor of shape given, with random values normally distributed having given mean & standard deviation.

In [12]:
sess.run(tf.random_normal((3,5),mean=6,stddev=3))

array([[ 7.278775 ,  4.7681856,  6.584076 ,  8.958192 , 10.119011 ],
       [ 9.529356 ,  3.311645 ,  5.220321 ,  5.740642 ,  7.057202 ],
       [ 7.274617 ,  6.412084 ,  4.7838373, 11.256926 ,  4.960513 ]],
      dtype=float32)

### tf.random_uniform()
`tf.random_uniform()` takes shape(tuple) as its argument. In addition, it also takes `minimum value` and `maximum value`.  This functions creates a tensor of shape given, with random values uniformly distributed from given minimum value to given maximum value.

In [13]:
sess.run(tf.random_uniform((3,5),minval=-10,maxval=10))

array([[ 9.752785  ,  6.934698  , -6.720121  , -5.8778644 , -0.8086567 ],
       [-0.57055664, -8.168974  ,  5.078869  ,  0.511179  ,  2.9104729 ],
       [-3.6444902 , -5.0551987 ,  3.7317133 ,  4.796791  ,  1.7103024 ]],
      dtype=float32)

### tf.random_poisson()
`tf.random_uniform()` takes shape(tuple) & `lambda` as its argument. This functions creates a tensor of shape given, with random values following poisson distribution with given lambda.

In [14]:
sess.run(tf.random_poisson(3,(3,5)))

array([[7., 3., 3., 3., 5.],
       [1., 2., 4., 0., 1.],
       [4., 1., 3., 3., 1.]], dtype=float32)

## Tensor Operations:

In [15]:
tensor=tf.constant([[1,2,3],[4,5,6]])

### .get_shape()
`.get_shape()` method returns shape of the tensor created.

In [16]:
tensor.get_shape()

TensorShape([Dimension(2), Dimension(3)])

### .eval()
`.eval()` method simply executes the tensor.<br>
__Note:__ To use `.eval()` method one must execute an `Interactive session` before using `.eval()` method.

In [17]:
sess=tf.InteractiveSession()

In [18]:
tensor.eval()

array([[1, 2, 3],
       [4, 5, 6]])

### tf.reshape()
`tf.reshape()` takes 2 arguments a `tensor` and `shape`. The function changes shape of given `tensor` to `shape` given.

In [19]:
sess.run(tf.reshape(tensor,(3,2)))

array([[1, 2],
       [3, 4],
       [5, 6]])

### tf.rank()
`tf.rank()` takes a `tensor` as its argument. The function provides number of dimensions.

In [20]:
sess.run(tf.rank(tensor))

2

### tf.device()
`tf.device()` lets you to place tensors on different devices such as CPUs, GPUs,etc.

In [21]:
with tf.device("/device:GPU:0"):
    const=tf.constant('Ankur Goswami')

### .dtype
`.dtype` attribute returns data type of the tensor object.

In [22]:
tensor.dtype

tf.int32

### .shape
`.shape` attribute returns shape of the tensor created.

In [23]:
tensor.shape

TensorShape([Dimension(2), Dimension(3)])

___
# Mathematical Operations:

Mathematical operations of Tensorflow are as same as NumPy. The only difference is that constants & variables need to be executed using a session in tensorflow.

___
# Tensorflow Graphs:

When you start TensorFlow, a default Graph is created, you can create additional graphs easily:

## Default Graph:

In [24]:
tf.get_default_graph()

## Creating Graphs:
`tf.Graph()` function lets you to create graphs.

In [25]:
graph=tf.Graph()
graph

## Graph Operations:

__To check whether the Graph is default or not__

In [26]:
graph is tf.get_default_graph()

False

### .as_default()
`.as_default()` method is sets a graph as a default graph.

In [27]:
with graph.as_default():
    print(graph is tf.get_default_graph())

True


___
# Tensorflow Variables :
A TensorFlow variable is the best way to represent shared, persistent state manipulated by your program.

## Creating Variables:

### tf.Variable()
`tf.Variable()` takes a value as its argument and creates a variable with that value.

In [28]:
var=tf.Variable([[9,8,7],[6,5,4]])

Instructions for updating:
Colocations handled automatically by placer.


In [29]:
sess.run(var)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

### tf.global_variables_initializer()
__Note:__ Declared and assigned variables do not get executed using a session, until and unless they are initialized. To intialize, we use `tf.global_variables_initializer()` function.

In [ ]:
sess.run(tf.global_variables_initializer())

In [ ]:
sess.run(var)

### tf.get_variable()
`tf.get_variable()` function takes 3 arguments `name`, `shape` & `initializer`. This function creates a variable with given `shape` and value(`initializer`) provided. If `initializer` is not provided, then it initializes with random values.

In [ ]:
variable = tf.get_variable("variable",(1,2,3),initializer=tf.constant_initializer(7))

In [ ]:
sess.run(tf.global_variables_initializer())
sess.run(variable)

___
# Tensorflow Placeholders:
Placeholders are initially empty & are used to feed in the actual training data. However, they do need a declared expected data type with an optional shape argument.

## Creating placeholders:

### tf.placeholder()
`tf.placeholder()` takes `data type` & `shape` as its arguments & creates a placeholder of given data type & shape.

In [30]:
placeholder=tf.placeholder(tf.float32,(None,6))

__Note:__ In above example, we have set `None` as we exactly don't know how many samples we are feeding in.

In [31]:
sess.run(placeholder,feed_dict={placeholder:[[1,2,3,4,5,6]]})

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

____

# TensorFlow's Model Training & Testing Procedure:

## Data Loading & Cleaning:

Data:
https://archive.ics.uci.edu/ml/datasets/pima+indians+diabetes

In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [47]:
diabetes = pd.read_csv('pima-indians-diabetes.csv')

In [48]:
diabetes.head()

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps   Insulin  \
0                6               0.743719        0.590164  0.353535  0.000000   
1                1               0.427136        0.540984  0.292929  0.000000   
2                8               0.919598        0.524590  0.000000  0.000000   
3                1               0.447236        0.540984  0.232323  0.111111   
4                0               0.688442        0.327869  0.353535  0.198582   

        BMI  Pedigree  Age  Class Group  
0  0.500745  0.234415   50      1     B  
1  0.396423  0.116567   31      0     C  
2  0.347243  0.253629   32      1     B  
3  0.418778  0.038002   21      0     B  
4  0.642325  0.943638   33      1     C

In [49]:
diabetes.columns

Index(['Number_pregnant', 'Glucose_concentration', 'Blood_pressure', 'Triceps',
       'Insulin', 'BMI', 'Pedigree', 'Age', 'Class', 'Group'],
      dtype='object')

In [50]:
cols_to_norm = ['Number_pregnant','Glucose_concentration',
                'Blood_pressure','Triceps','Insulin','BMI','Pedigree']

In [51]:
diabetes[cols_to_norm]=diabetes[cols_to_norm].apply(lambda x: (x-x.min())/(x.max()-x.min()))

In [52]:
diabetes.head()

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps   Insulin  \
0         0.352941               0.743719        0.590164  0.353535  0.000000   
1         0.058824               0.427136        0.540984  0.292929  0.000000   
2         0.470588               0.919598        0.524590  0.000000  0.000000   
3         0.058824               0.447236        0.540984  0.232323  0.111111   
4         0.000000               0.688442        0.327869  0.353535  0.198582   

        BMI  Pedigree  Age  Class Group  
0  0.500745  0.234415   50      1     B  
1  0.396423  0.116567   31      0     C  
2  0.347243  0.253629   32      1     B  
3  0.418778  0.038002   21      0     B  
4  0.642325  0.943638   33      1     C

## Feature Selection:

### Continuous Features

* Number of times pregnant
* Plasma glucose concentration a 2 hours in an oral glucose tolerance test
* Diastolic blood pressure (mm Hg)
* Triceps skin fold thickness (mm)
* 2-Hour serum insulin (mu U/ml)
* Body mass index (weight in kg/(height in m)^2)
* Diabetes pedigree function

### tf.feature_column.numeric_column()
`tf.feature_column.numeric_column()` takes in `key` and `shape` of the input. The given column must be a numeric column. This function considers the given column as a Numerical Feauture column. 

In [53]:
num_preg=tf.feature_column.numeric_column('Number_pregnant')
plasma_gluc=tf.feature_column.numeric_column('Glucose_concentration')
dias_press=tf.feature_column.numeric_column('Blood_pressure')
tricep=tf.feature_column.numeric_column('Triceps')
insulin=tf.feature_column.numeric_column('Insulin')
bmi=tf.feature_column.numeric_column('BMI')
diabetes_pedigree=tf.feature_column.numeric_column('Pedigree')
age=tf.feature_column.numeric_column('Age')

### Categorical Features
If you know the set of all possible feature values of a column and there are only a few of them, you can use `categorical_column_with_vocabulary_list`. If you don't know the set of possible values in advance you can use `categorical_column_with_hash_bucket`

### tf.feature_column.categorical_column_with_vocabulary_list()
`tf.feature_column.categorical_column_with_vocabulary_list()` takes a `key` and a `vocabulary list` as its input arguments. `Vocabulary list` contains unique values that comes in the gven column. The given column must be a categorical column. This function considers the given column as a Categorical Feauture column. 

In [54]:
assigned_group_1=tf.feature_column.categorical_column_with_vocabulary_list('Group',['A','B','C','D'])

### tf.feature_column.categorical_column_with_hash_bucket()
`tf.feature_column.categorical_column_with_hash_bucket()` takes a `key` & `hash bucket size` as its arguments. `Hash bucket size` is the number of unique values that the given colummn has. One can even provide a number which is greater than the number of categories. The given column must be a categorical column. This function considers the given column as a Categorical Feauture column.

In [55]:
assigned_group_2=tf.feature_column.categorical_column_with_hash_bucket('Group', hash_bucket_size=10)

### tf.feature_column.embedding_column()
`tf.feature_column.embedding_column()` takes a `categorical column` & `dimension` as its arguments. This function is only useful when our model is dealing with the __neural networks__.

In [73]:
embedded_group_column = tf.feature_column.embedding_column(assigned_group_1, dimension=4)

### Converting Continuous to Categorical

### tf.feature_column.bucketized_column()
`tf.feature_column.bucketized_column()` takes in `source column` & `boundaries` as its arguments. The function categorizes numerical data to categories.

In [56]:
age_buckets = tf.feature_column.bucketized_column(age, boundaries=[20,30,40,50,60,70,80])

### Feature Columns:

In [57]:
feat_cols=[num_preg,plasma_gluc,dias_press,tricep,insulin,bmi,diabetes_pedigree,assigned_group_1,age_buckets]

In [58]:
x_data=diabetes.drop('Class',axis=1)
labels=diabetes['Class']

In [59]:
X_train,X_test,y_train,y_test=train_test_split(x_data,labels,test_size=0.33,random_state=42)

## Input Function:
An input function defines the input of your model. It contains type of input (Pandas or NumPy), input values, batch size, number of iterations,etc.

### tf.estimator.inputs.pandas_input_fn()
`tf.estimator.inputs.pandas_input_fn()` takes `feature matrix`, `vector of predictions`, `batch size`, `number of iterations`, `shuffle`,etc. The `feature matrix` & `vector of predictions` must be of pandas type. This lets the model to train/test in `batches` in given `iterations`. `Shuffle` lets to randomize inputs.

In [60]:
input_train_func=tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=10,num_epochs=1000,shuffle=True)
input_test_func=tf.estimator.inputs.pandas_input_fn(x=X_test,y=y_test,batch_size=10,num_epochs=1000,shuffle=False)

### tf.estimator.inputs.numpy_input_fn()
This is same as `tf.estimator.inputs.pandas_input_fn()` but in place of pandas it takes numpy type of data.

## Model Creation:

### tf.estimator.LinearClassifier()
`tf.estimator.LinearClassifier()` takes in `featue columns` & `no of classes` as its arguments. This instantiates a Linear Classifier model for given `featue columns` & `no of classes`. This classifier works linearly.

In [61]:
model=tf.estimator.LinearClassifier(feature_columns=feat_cols,n_classes=2)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Ankur Goswami\\AppData\\Local\\Temp\\tmp0xwg8e4k', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001FE54337128>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


### tf.estimator.DNNClassifier()
`tf.estimator.DNNClassifier()` is a Neural network based Classifier.

### tf.estimator.DNNLinearCombinedClassifier()
`tf.estimator.DNNLinearCombinedClassifier()` is a Classifier which is a combination of Linear Classifier & Neural network based Classifier.

### tf.estimator.LinearRegressor()
`tf.estimator.LinearRegressor()` is a Linear Regressor.

### tf.estimator.DNNRegressor()
`tf.estimator.DNNRegressor()` is a Neural network based Regressor.

### tf.estimator.DNNLinearCombinedRegressor()
`tf.estimator.DNNLinearCombinedRegressor()` is a Regressor which is a combination of Linear Regressor & Neural network based Regressor.

## Model Training:

### model.train()
`.train()` method takes an `input function` & `number of steps`  as its function parameters. This method fits the model for the given input data.

In [62]:
model.train(input_fn=input_test_func,steps=1000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Ankur Goswami\AppData\Local\Temp\tmp0xwg8e4k\model.ckpt.
INFO:tensorflow:loss = 6.931472, step = 1
INFO:tensorflow:global_step/sec: 137.551
INFO:tensorflow:loss = 4.346552, step = 101 (0.730 sec)
INFO:tensorflow:global_step/sec: 351.816
INFO:tensorflow:loss = 6.0716467, step = 201 (0.284 sec)
INFO:tensorflow:global_step/sec: 394.752
INFO:tensorflow:loss = 3.275

## Evaluation:

### model.evaluate()
`.evaluate()` method is takes an `input function` & `number of steps` as its function parameters. This method evaluates various parameters such as `accuracy`, `loss`, `precision`,etc.

In [68]:
results=model.evaluate(input_fn=input_train_func)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-07-15T09:36:20Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ankur Goswami\AppData\Local\Temp\tmp0xwg8e4k\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-07-15-09:38:21
INFO:tensorflow:Saving dict for global step 1000: accuracy = 0.7140078, accuracy_baseline = 0.64591444, auc = 0.7467563, auc_precision_recall = 0.58532095, average_loss = 0.56621677, global_step = 1000, label/mean = 0.3540856, loss = 5.6621675, precision = 0.6335878, prediction/mean = 0.3501416, recall = 0.45604396
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: C:\Users\Ankur Goswami\AppData\Local\Temp\tmp0xwg8e4k\model.ckpt-1000


In [69]:
results

{'accuracy': 0.7140078,
 'accuracy_baseline': 0.64591444,
 'auc': 0.7467563,
 'auc_precision_recall': 0.58532095,
 'average_loss': 0.56621677,
 'label/mean': 0.3540856,
 'loss': 5.6621675,
 'precision': 0.6335878,
 'prediction/mean': 0.3501416,
 'recall': 0.45604396,
 'global_step': 1000}

## Predictions:

### model.predict()
`.predict()` method takes an `input function` as its function parameters and generates predictions for given `output function`.

In [71]:
predictions=model.predict(input_fn=input_test_func)

In [72]:
list(predictions)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ankur Goswami\AppData\Local\Temp\tmp0xwg8e4k\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'logits': array([-0.08598799], dtype=float32),
  'logistic': array([0.47851625], dtype=float32),
  'probabilities': array([0.5214838 , 0.47851628], dtype=float32),
  'class_ids': array([0], dtype=int64),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([-1.3823314], dtype=float32),
  'logistic': array([0.20063484], dtype=float32),
  'probabilities': array([0.7993651 , 0.20063482], dtype=float32),
  'class_ids': array([0], dtype=int64),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([-1.829609], dtype=float32),
  'logistic': array([0.13828486], dtype=float32),
  'probabilities': array([0.86171514, 0.13828485], dtype=float32),
  'class_ids': array([0], dtype=int64),
  'classes': array([b'0'], dtype=object)},
 {'logits': array([-0.1054644], dtype=float32),
  'logistic': array([0.47365832], dtype=float32),
  'probabilities': array([0.5263417, 0.4736583], dtype=float32),
  'class_ids': array([0], dtype=int64),
  'classes': array([b'0'], dtype=object)},
 {'logits'

___